library/core/urls.py
from django.urls import path
from . import views

app_name = 'core'
urlpatterns = [
    path('', views.index_view, name='index'),
    path('register', views.register_view, name='register'),
    path('index', views.index_view, name='index'),
    path('authors', views.authors_view, name='authors'),
    path('author/create', views.create_author_view, name='create_author'),
]

library/urls.py
from django.urls import path, include

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('', include('library.core.urls')),
]

library/core/models.py
from datetime import date
from django.core.validators import MinLengthValidator
from django.db import models
from django.utils.translation import gettext_lazy as _


class Author(models.Model):
    """ Author class """
    first_name = models.CharField(_("First name"), max_length=128, validators=[MinLengthValidator(2)])
    last_name = models.CharField(_("Last name"), max_length=128, validators=[MinLengthValidator(2)])

    def name(self):
        return f"{self.first_name} {self.last_name}"

    def __str__(self):
        return self.name()

    class Meta:
        ordering = ['last_name', 'first_name', 'id']
        verbose_name = _("Author")
        verbose_name_plural = _("Authors")


class Book(models.Model):
    """ Book class """
    title = models.CharField(_("Title"), max_length=128, validators=[MinLengthValidator(2)])
    year = models.PositiveSmallIntegerField(_("Year"), choices=((y, y) for y in range(1950, date.today().year + 1)),
                                            default=date.today().year)

    authors = models.ManyToManyField(Author)

    class Meta:
        ordering = ['title']
        verbose_name = _("Book")
        verbose_name_plural = _("Books")

library/core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _
from django.forms import ModelForm
from .models import Author


class CreateAuthorForm(ModelForm):
    class Meta:
        model = Author
        fields = ['first_name', 'last_name']


class RegisterForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text=_("Optional."), label=_("First name"))
    last_name = forms.CharField(max_length=30, required=False, help_text=_("Optional."), label=_("Last name"))
    email = forms.EmailField(max_length=64)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')

library/core/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.views.generic import CreateView, FormView, ListView, TemplateView
from django.urls import reverse_lazy
from .forms import CreateAuthorForm, RegisterForm
from .models import Author


class IndexView(TemplateView):
    """ Index view """
    template_name = "core/index.html"


index_view = IndexView.as_view()


class AuthorsView(ListView):
    """ Authors view """
    model = Author
    paginate_by = 10


authors_view = AuthorsView.as_view()


class CreateAuthorView(LoginRequiredMixin, CreateView):
    """ Create author view """
    model = Author
    success_url = reverse_lazy('core:authors')
    form_class = CreateAuthorForm
    login_url = reverse_lazy('login')


create_author_view = CreateAuthorView.as_view()


class RegisterView(FormView):
    """ Register form """
    template_name = 'registration/register.html'
    model = User
    form_class = RegisterForm
    success_url = reverse_lazy('core:index')

    def post(self, request, *args, **kwargs):
        response = super(RegisterView, self).post(request, *args, **kwargs)
        if response:
            form = self.get_form()
            form.save()
        return response


register_view = RegisterView.as_view()

library/core/templates/core/author_form.html
{% extends 'core/base.html' %}

{% load bootstrap4 i18n %}

{% block content %}
<div class="container">
    <form class="form" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% bootstrap_button _("Save") button_type="submit" button_class="btn-primary" %}
        <a href="{% url 'core:authors' %}" class="btn btn-light">{% trans 'Cancel' %}</a>
    </form>
</div>
{% endblock %}

library/core/templates/core/author_list.html
{% extends 'core/base.html' %}

{% load bootstrap4 i18n %}

{% block bootstrap4_title %}
    {% trans 'Authors' %}
{% endblock %}


{% block content %}
    {% if page_obj %}
        {% for author in page_obj %}
            <div>
                {{ author.name }}
                <ul>
                {% for book in author.book_set.all %}
                    <li>
                        {{ book.title }}  {{ book.year }}
                        {% for a in book.authors.all %}
                            {{ a }}
                        {% endfor %}
                    </li>
                {% endfor %}
                </ul>
            </div>

        {% endfor %}
        {% bootstrap_pagination page_obj %}
    {% else %}
    No authors
    {% endif %}
{% endblock %}

library/core/templates/core/base.html
{% extends 'bootstrap4/bootstrap4.html' %}

{% load bootstrap4 i18n %}

{% block bootstrap4_title %}
Library
{% endblock %}

{% block bootstrap4_extra_head %}
    {% bootstrap_javascript jquery='full' %}
{% endblock %}


{% block bootstrap4_before_content %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'core:index' %}">Library</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'core:authors' %}">{% trans 'Authors' %}</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'core:create_author' %}">{% trans 'Create author' %}</a>
      </li>
    </ul>

    <ul class="navbar-nav ml-auto">
      {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}">{% trans 'Logout' %} ({{ request.user.username }})</a>
        </li>
        <li>
          <a class="nav-link" href="{% url 'password_change' %}">{% trans 'Change password' %}</a>
        </li>
      {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'core:register' %}">{% trans 'Register' %}</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'login' %}">{% trans 'Login' %}</a>
        </li>
      {% endif %}
    </ul>
  </div>
</nav>
{% endblock %}

{% block bootstrap4_content %}
    {% block content %}
    {% endblock %}
{% endblock %}

{% block bootstrap4_after_content %}
{% endblock %}

library/core/templates/core/index.html
{% extends 'core/base.html' %}

{% load i18n %}

{% block content %}

{% blocktrans %}
Hello!
Welcome on my page!
{% endblocktrans %}

{% endblock %}